name: Build Windows wheel (py311)

on:
  push:
  workflow_dispatch:

jobs:
  win_py311:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"   # можно и "3.11"

      - name: Build wheel
        run: |
          python -m pip install -U pip build
          python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-py311-wheel
          path: dist/*.whl
